In [1]:
a = round(3.19 +3.19 + 3.19+3.19 +3.19 + 3.19 +3.19 +3.19 , 2)
b = 3.19 *8

In [2]:
print(a)
print(b)

25.52
25.52


In [3]:
a==b

True

In [4]:
x=3.19 +3.19 + 3.19+3.19
y=3.19 *4
print(x)
print(y)

12.76
12.76


In [5]:
x==y

True

In [6]:
f  = open('test.txt', 'w+')
print("Simplilearn", file = f)
f.close()

#### Agenda:

- Fundamentals of Numpy
    * Advantages
    * Installation
- Array 
    `* Creating Numpy array

Numpy is an opensource  librarry that is primarily used for mathematical and scientific calculations. it allows the usage of Arras which are not available as data structure in python core modules

In [7]:
#Install Numpy

!pip install numpy

Defaulting to user installation because normal site-packages is not writeable

[notice] A new release of pip is available: 23.3 -> 24.0
[notice] To update, run: pip install --upgrade pip


In [8]:
# Importing numpy

In [9]:
import numpy as np

In [10]:
a =  np.array([10,20,30,40.5])

In [11]:
print(a)

[10.  20.  30.  40.5]


In [12]:
b = [10,20,30,40.5]
print(b)

[10, 20, 30, 40.5]


In [13]:
print(type(a))

<class 'numpy.ndarray'>


In [14]:
print(type(b))

<class 'list'>


In [15]:
print(id(a[0]))
print(id(a[1]))
print(id(a[2]))
print(id(a[3]))

140131027037424
140131027036880
140131027037328
140131027037328


In [16]:
print(id(b[0]))
print(id(b[1]))
print(id(b[2]))
print(id(b[3]))

140131628909072
140131628909392
140131628909712
140131581442992


In [17]:
import numpy as np
import time # using for capturingting the epoch(unix) time -  time is seconds/ms elasped sinch epoch( Jan 1st 1970 00:00:00)

In [18]:
time.time()

1708612870.205827

In [19]:
time.time()

1708612870.2955217

In [20]:
1708527116.5961807 - 1708527033.5490918

83.04708886146545

In [21]:
X = np.random.rand(100000000)

In [22]:
start = time.time()
avg = sum(X)/100000000
stop = time.time()
print(stop-start)

5.620566368103027


In [23]:
start = time.time()
avgnp = np.mean(X)
stop = time.time()
print(stop-start)

0.055956363677978516


In [24]:
# Create Array - Syntax is 
# numpy.array(<lists>)

In [25]:
# Create 0darray
X = np.array(34)
print(X)
print(X.ndim)

34
0


In [26]:
# Create 1darray
X = np.array([1,2,3,4,5])
print(X)
print(X.ndim)

[1 2 3 4 5]
1


In [27]:
# Create 2darray
X = np.array([[1,2,3,4,5], [11,12,13,14,15]])
print(X)
print(X.ndim)

[[ 1  2  3  4  5]
 [11 12 13 14 15]]
2


In [28]:
# Create 2darray
X = np.array([[[1,2,3,4,5], [11,12,13,14,15]], [[1,2,3,4,5], [11,12,13,14,15]]])
print(X)
print(X.ndim)

[[[ 1  2  3  4  5]
  [11 12 13 14 15]]

 [[ 1  2  3  4  5]
  [11 12 13 14 15]]]
3


In [29]:
X =  np.array([[1,2], [2,3], [3,4]])
print(X)

[[1 2]
 [2 3]
 [3 4]]


In [30]:
Y = np.array([[1,2,3,4]])

In [31]:
Y.ndim

2

In [32]:
print(Y)

[[1 2 3 4]]


In [33]:
# Attributes and Functions

In [34]:
array1 = np.array([[1,2,3], [11,12,13]])

In [35]:
array1 = np.array([[1,2,3], [11,12,13]])
print(array1)
print("No of dimensions : ", array1.ndim)
print("Shape of array : ", array1.shape)
print("Size of array : ", array1.size)
print("datatype of array elements: ", array1.dtype)
print("length  of one array element in memory in bytes: ", array1.itemsize)

[[ 1  2  3]
 [11 12 13]]
No of dimensions :  2
Shape of array :  (2, 3)
Size of array :  6
datatype of array elements:  int64
length  of one array element in memory in bytes:  8


In [36]:
array2 = np.array([[[1,2,3], [11,12,13]]])
print(array2)
print("No of dimensions : ", array2.ndim)
print("Shape of array : ", array2.shape)
print("Size of array : ", array2.size)
print("datatype of array elements: ", array2.dtype)
print("length  of one array element in memory in bytes: ", array2.itemsize)

[[[ 1  2  3]
  [11 12 13]]]
No of dimensions :  3
Shape of array :  (1, 2, 3)
Size of array :  6
datatype of array elements:  int64
length  of one array element in memory in bytes:  8


In [37]:
array3 = np.array([[[1,2,3,4,5], [11,12,13,14,15]], [[1,2,3,4,5], [11,12,13,14,15]]])

In [38]:
print(array3.shape)

(2, 2, 5)


In [39]:
print(array3)

[[[ 1  2  3  4  5]
  [11 12 13 14 15]]

 [[ 1  2  3  4  5]
  [11 12 13 14 15]]]


In [40]:
array4 = np.arange(1,28).reshape(3,3,3)

In [41]:
print(array4)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [42]:
array4.shape

(3, 3, 3)

In [43]:
# Basic Functions

In [44]:
#reshape
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [45]:
arr.shape

(12,)

In [46]:
newarr = arr.reshape(2,3,2)

In [47]:
newarr

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [48]:
newarr = newarr.reshape(4,3)

In [49]:
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [50]:
newarr.reshape(12,)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [51]:
newarr.reshape(1,12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [52]:
np.ravel(newarr, order = 'F') # Fortran Based Access

array([ 1,  4,  7, 10,  2,  5,  8, 11,  3,  6,  9, 12])

In [53]:
np.ravel(newarr, order = 'C') # C Based Access

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [54]:
newarr.shape

(4, 3)

In [55]:
newarr.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [56]:
# Transpose

In [57]:
newarr.T

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [58]:
newarr.transpose()

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [59]:
# Arithmetic, statistical , string ops in numpy

In [60]:
# Arithmetic OPerations -  are done one element wise basis

In [61]:
a = np.array([10,20,30])
b = np.array([2,4,5])

In [62]:
a+b

array([12, 24, 35])

In [63]:
np.add(a,b)

array([12, 24, 35])

In [64]:
a-b

array([ 8, 16, 25])

In [65]:
np.subtract(a,b)

array([ 8, 16, 25])

In [66]:
a*b

array([ 20,  80, 150])

In [67]:
np.multiply(a,b)

array([ 20,  80, 150])

In [68]:
a/b

array([5., 5., 6.])

In [69]:
np.divide(a,b)

array([5., 5., 6.])

In [70]:
a**b

array([     100,   160000, 24300000])

In [71]:
np.power(a,b)

array([     100,   160000, 24300000])

In [72]:
print(-5/2)

-2.5


In [73]:
print(-5//2)

-3


In [74]:
#  // =  Floor Division -  nearest integer moving towrds negative infinity

In [75]:
# Statistical Functions

In [76]:
ar =  np.array([[34,12,11], [23,56,12],[23,34,2]])

In [77]:
# median

In [78]:
np.median(ar)

23.0

In [79]:
np.percentile(ar, 50)

23.0

In [80]:
np.mean(ar)

23.0

In [81]:
np.std(ar)

15.484759532449246

In [82]:
np.var(ar)

239.77777777777777

In [83]:
15.484759532449246**2

239.7777777777778

In [84]:
# String Functions

In [85]:
"Hello" + "World"

'HelloWorld'

In [86]:
"Hello" * 2

'HelloHello'

In [87]:
x =  np.array(['Hello', 'Welcome'])
y = np.array(['Learners', "Everyone"])

In [89]:
np.char.add(x,y)

array(['HelloLearners', 'WelcomeEveryone'], dtype='<U15')

In [90]:
s1 =  "Hello All , How are you"

In [91]:
np.char.replace(s1, 'All', 'Everyone')

array('Hello Everyone , How are you', dtype='<U28')

In [92]:
np.char.upper(s1)

array('HELLO ALL , HOW ARE YOU', dtype='<U23')

In [93]:
np.char.isalnum(s1)

array(False)

In [100]:
c =  np.array([1, 2.5, True, "Simplilearn1111111111111111111111111111111111111111111111111111"])

In [101]:
print(c)

['1' '2.5' 'True'
 'Simplilearn1111111111111111111111111111111111111111111111111111']


In [102]:
c

array(['1', '2.5', 'True',
       'Simplilearn1111111111111111111111111111111111111111111111111111'],
      dtype='<U63')

In [97]:
d =  np.array(['1', '2.5', 'True', "Simplilearn"])
d

array(['1', '2.5', 'True', 'Simplilearn'], dtype='<U11')

In [99]:
int(False)

0

In [103]:
# arange function -  allows to create 1darray of numbers with specified interval between two consecutive values. 
# syntax - np.arange(start = 0, stop, step =1)

In [104]:
X = np.arange(10) # np.arange(start = 0, stop=10, step =1)
print(X)

[0 1 2 3 4 5 6 7 8 9]


In [106]:
X = np.arange(4,25) # np.arange(start = 4, stop=25, step =1)
print(X)

[ 4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [107]:
X = np.arange(4,25,2) # np.arange(start = 4, stop=25, step =2)
print(X)

[ 4  6  8 10 12 14 16 18 20 22 24]


In [108]:
X = np.arange(4,25,-2) # np.arange(start = 4, stop=25, step =-2)
print(X)

[]


In [109]:
X = np.arange(0,-10,-2) # np.arange(start = 0, stop=-10, step =-2)
print(X)

[ 0 -2 -4 -6 -8]


In [111]:
'aBc'<'aBC'

False

In [116]:
# Linspace -  Linear Spacing -  Allows to generate specific count of equidistant numbers in a closed interval
# Syntax =  np.linspace(start(inclusive),end(inclusive), number of values)

In [130]:
v = np.linspace(1,10,10)
print(v)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [131]:
v = np.linspace(1,10,10, endpoint = False)
print(v)

[1.  1.9 2.8 3.7 4.6 5.5 6.4 7.3 8.2 9.1]


In [132]:
np.linspace(1,3, 3, endpoint =False)

array([1.        , 1.66666667, 2.33333333])

In [133]:
# Indexing and slicing

In [135]:
onedarray = np.array([1,2,3,4,5,6])
twodarray = np.array([[1,2,3],[4,5,6]])
threedarray = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[11,12,13]]])

In [136]:
print(onedarray)

[1 2 3 4 5 6]


In [137]:
print(onedarray[4])

5


In [138]:
print(onedarray[-2])

5


In [140]:
onedarray[4] = 15
print(onedarray)

[ 1  2  3  4 15  6]


In [143]:
onedarray[-1] = 's'

ValueError: invalid literal for int() with base 10: 's'

In [144]:
print(twodarray)

[[1 2 3]
 [4 5 6]]


In [145]:
twodarray[1,1]

5

In [146]:
twodarray[1,-2] = 16
print(twodarray)

[[ 1  2  3]
 [ 4 16  6]]


In [147]:
print(threedarray)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [11 12 13]]]


In [148]:
threedarray[-1,0,2]

9

In [150]:
threedarray[1,1,2]

13

In [151]:
# Array Slicing

In [153]:
print(onedarray)

[ 1  2  3  4 15  6]


In [156]:
onedarray[[1,2,3,4]]

array([ 2,  3,  4, 15])

In [158]:
onedarray[1:5:2]

array([2, 4])

In [159]:
print(twodarray)

[[ 1  2  3]
 [ 4 16  6]]


In [162]:
twodarray[0:2,1]

array([ 2, 16])

In [161]:
twodarray[1,1]

16

In [163]:
twodarray[0:2,[0,2]]

array([[1, 3],
       [4, 6]])

In [167]:
twodarray[0:2][1:2]

array([[ 4, 16,  6]])

In [168]:
twodarray[0:2,0::2]

array([[1, 3],
       [4, 6]])

In [169]:
twodarray[0:2]

array([[ 1,  2,  3],
       [ 4, 16,  6]])

In [170]:
X =  np.arange(1,10).reshape(3,3)

In [171]:
print(X)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [172]:
X[0:3:2, 0:3:2]

array([[1, 3],
       [7, 9]])

In [178]:
X[1:3, 1:3]

array([[5, 6],
       [8, 9]])

In [179]:
print(threedarray)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [11 12 13]]]


In [180]:
threedarray[:,1,1:]

array([[ 5,  6],
       [12, 13]])

In [181]:
threedarray[1,:,1:]

array([[ 8,  9],
       [12, 13]])

In [204]:
p = np.array((",".join(str(x) for x in threedarray[0,:,2]) +',' + ",".join(str(x) for x in threedarray[1,:,0])).split(','), dtype ='int32')

In [205]:
p

array([ 3,  6,  7, 11], dtype=int32)

In [208]:
threedarray.reshape(12,)[[2,5,6,9]]

array([ 3,  6,  7, 11])